version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:6060
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 6060:6060
    env_file:
      - ./.env.dev